#!/usr/bin/env bash
#
# snapshot-local-data.sh
#
# Capture the CURRENT local database's *data* (auth accounts + application rows)
# into a gitignored seed file that `supabase db reset` replays automatically.
#
#   Schema + system reference data ........ owned by migrations/
#   Per-developer local data (this file) .. supabase/seeds/dev_data.local.sql
#
# Run it whenever you want your current local data to survive the next reset:
#   npm run db:snapshot
#
# The generated file is applied via config.toml [db.seed] sql_paths after all
# migrations run, so it can rely on the full schema already existing.
#
set -euo pipefail

CONTAINER="${SUPABASE_DB_CONTAINER:-supabase_db_famtastic}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/supabase/seeds"
OUT="$OUT_DIR/dev_data.local.sql"

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  echo "error: db container '$CONTAINER' is not running. Start it with 'npm run db:start'." >&2
  echo "       (override the name with SUPABASE_DB_CONTAINER=... if your project id differs.)" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

psql() { docker exec -i "$CONTAINER" psql -U postgres -d postgres "$@"; }
# --column-inserts => portable one-row-per-statement INSERTs (no COPY-from-stdin,
# which the seed runner batches poorly). We keep only the INSERT lines.
dump() { docker exec -i "$CONTAINER" pg_dump -U postgres -d postgres \
           --data-only --column-inserts --no-owner "$@" | grep '^INSERT INTO' || true; }

# Every base table in public except the PostGIS reference table (recreated by the
# extension). Discovered dynamically so new tables are captured automatically.
mapfile -t TABLES < <(psql -At -c "
  SELECT quote_ident(schemaname)||'.'||quote_ident(tablename)
  FROM pg_tables
  WHERE schemaname = 'public' AND tablename <> 'spatial_ref_sys'
  ORDER BY tablename;")

if [ "${#TABLES[@]}" -eq 0 ]; then
  echo "error: no public tables found - has the schema been applied?" >&2
  exit 1
fi

PUB_ARGS=()
for t in "${TABLES[@]}"; do PUB_ARGS+=(-t "$t"); done
TRUNCATE_LIST="$(IFS=', '; echo "${TABLES[*]}")"

{
  echo "-- ============================================================================"
  echo "-- GENERATED by scripts/snapshot-local-data.sh  (npm run db:snapshot)"
  echo "-- Local developer data snapshot - DO NOT EDIT BY HAND. Gitignored."
  echo "-- Replayed after migrations by 'supabase db reset' (config.toml [db.seed])."
  echo "-- ============================================================================"
  echo
  echo "BEGIN;"
  echo
  echo "-- 1. Auth accounts. Inserting auth.users fires the handle_new_user trigger,"
  echo "--    which creates bare public.profiles rows; step 2 clears them so the real"
  echo "--    profile rows from step 3 win."
  dump -t auth.users -t auth.identities
  echo
  echo "-- 2. Clear anything migrations/triggers pre-created so this snapshot is"
  echo "--    authoritative (TRUNCATE ... CASCADE is order-independent)."
  echo "TRUNCATE $TRUNCATE_LIST CASCADE;"
  echo
  echo "-- 3. Application data."
  dump "${PUB_ARGS[@]}"
  echo
  echo "COMMIT;"
} > "$OUT"

echo "Wrote $OUT"
echo "  auth rows:   $(grep -c '^INSERT INTO auth\.' "$OUT" || true)"
echo "  public rows: $(grep -c '^INSERT INTO public\.' "$OUT" || true)"
